printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: none
bracketSpacing: false
jsxBracketSameLine: true
bracketSameLine: false
arrowParens: avoid
proseWrap: preserve